# Generated by Django 2.2.4 on 2019-09-12 21:47

from django.db import migrations, models
import doc.utility


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='image',
            field=models.ImageField(blank=True, upload_to=doc.utility.upload_header_image),
        ),
    ]
